### ISSUE TITLE
Front-end: Protótipo

### ISSUE THREAD

**Issue by RodrigoViniciusAmaral** [AparicioFermiano/EventTrack#3]
Desenvolver o protótipo de todas as telas do site. Indicar as funcionalidades dos elementos. (Levar em consideração a responsividade para dispositivos mobile e como os elementos se comportarão nesses casos)

**Comment by Luukitas** [comment]
- [x] Tela de home (com os eventos disponíveis)
- [x] tela de cadastro usuario comum
- [x] tela de cadastro usuario admin
- [x] tela login
- [x] tela de cadastro festa
- [x] tela detalhe de festa (com opção compra)
- [x] tela de relatórios
- [x] tela ingressos comprados
- [x] tela meus dados
- [x] tela recuperar senha
